options:
    advertised_hostname:
        description: Advertised hostname
        type: string
        default: "prometheus"
    advertised_port:
        description: Prometheus Port
        type: int
        default: 9090
    web_subpath:
        description: Subpath for accessing Prometheus
        type: string
        default: /
    default_target:
        description: Default target to be added in Prometheus
        type: string
        default: ""
