options:
    advertised-hostname:
        description: Advertised hostname
        type: string
        default: "prometheus"
    advertised-port:
        description: Prometheus Port
        type: int
        default: 9090
    web-subpath:
        description: Subpath for accessing Prometheus
        type: string
        default: /
